# Generated by Django 5.2.4 on 2025-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('room_number', models.IntegerField()),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
    ]
